import type { editor } from 'monaco-editor';

export const darkTheme: editor.IStandaloneThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'cdd6f4', background: '1e1e2e' },
    { token: 'comment', foreground: '6c7086', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'cba6f7' },
    { token: 'string', foreground: 'a6e3a1' },
    { token: 'number', foreground: 'fab387' },
    { token: 'type', foreground: '89dceb' },
    { token: 'function', foreground: '89b4fa' },
    { token: 'variable', foreground: 'cdd6f4' },
    { token: 'constant', foreground: 'fab387' },
    { token: 'operator', foreground: '94e2d5' },
    { token: 'delimiter', foreground: '9399b2' },
    { token: 'tag', foreground: 'cba6f7' },
    { token: 'attribute.name', foreground: '89b4fa' },
    { token: 'attribute.value', foreground: 'a6e3a1' },
    { token: 'regexp', foreground: 'f38ba8' },
  ],
  colors: {
    'editor.background': '#1e1e2e',
    'editor.foreground': '#cdd6f4',
    'editor.lineHighlightBackground': '#2a2b3d',
    'editor.selectionBackground': '#45475a',
    'editor.inactiveSelectionBackground': '#31324480',
    'editorCursor.foreground': '#f5e0dc',
    'editorWhitespace.foreground': '#45475a40',
    'editorIndentGuide.background': '#45475a40',
    'editorIndentGuide.activeBackground': '#45475a',
    'editorLineNumber.foreground': '#6c7086',
    'editorLineNumber.activeForeground': '#cdd6f4',
    'editorWidget.background': '#181825',
    'editorWidget.border': '#45475a',
    'editorSuggestWidget.background': '#181825',
    'editorSuggestWidget.border': '#45475a',
    'editorSuggestWidget.selectedBackground': '#313244',
    'editorSuggestWidget.highlightForeground': '#89b4fa',
    'editorBracketMatch.background': '#45475a40',
    'editorBracketMatch.border': '#89b4fa',
    'scrollbarSlider.background': '#45475a40',
    'scrollbarSlider.hoverBackground': '#45475a80',
    'scrollbarSlider.activeBackground': '#45475aCC',
  },
};
