import type { editor } from 'monaco-editor';

export const highContrastTheme: editor.IStandaloneThemeData = {
  base: 'hc-black',
  inherit: true,
  rules: [
    { token: '', foreground: 'ffffff', background: '000000' },
    { token: 'comment', foreground: 'a0a0a0', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'c586ff' },
    { token: 'string', foreground: '00ff00' },
    { token: 'number', foreground: 'ffaa00' },
    { token: 'type', foreground: '6fc3ff' },
    { token: 'function', foreground: '6fc3ff' },
    { token: 'variable', foreground: 'ffffff' },
    { token: 'constant', foreground: 'ffaa00' },
    { token: 'operator', foreground: '00ffff' },
    { token: 'delimiter', foreground: 'e0e0e0' },
    { token: 'tag', foreground: 'c586ff' },
    { token: 'attribute.name', foreground: '6fc3ff' },
    { token: 'attribute.value', foreground: '00ff00' },
    { token: 'regexp', foreground: 'ff3333' },
  ],
  colors: {
    'editor.background': '#000000',
    'editor.foreground': '#ffffff',
    'editor.lineHighlightBackground': '#1a1a1a',
    'editor.lineHighlightBorder': '#ffffff30',
    'editor.selectionBackground': '#264f78',
    'editor.inactiveSelectionBackground': '#264f7840',
    'editorCursor.foreground': '#ffffff',
    'editorWhitespace.foreground': '#ffffff30',
    'editorIndentGuide.background': '#ffffff20',
    'editorIndentGuide.activeBackground': '#ffffff60',
    'editorLineNumber.foreground': '#a0a0a0',
    'editorLineNumber.activeForeground': '#ffffff',
    'editorWidget.background': '#0a0a0a',
    'editorWidget.border': '#ffffff',
    'editorSuggestWidget.background': '#0a0a0a',
    'editorSuggestWidget.border': '#ffffff',
    'editorSuggestWidget.selectedBackground': '#1a1a1a',
    'editorSuggestWidget.highlightForeground': '#6fc3ff',
    'editorBracketMatch.background': '#264f7840',
    'editorBracketMatch.border': '#6fc3ff',
    'scrollbarSlider.background': '#ffffff20',
    'scrollbarSlider.hoverBackground': '#ffffff40',
    'scrollbarSlider.activeBackground': '#ffffff60',
    contrastBorder: '#ffffff',
    contrastActiveBorder: '#6fc3ff',
  },
};
