import type { editor } from 'monaco-editor';

export const lightTheme: editor.IStandaloneThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: '4c4f69', background: 'eff1f5' },
    { token: 'comment', foreground: '8c8fa1', fontStyle: 'italic' },
    { token: 'keyword', foreground: '8839ef' },
    { token: 'string', foreground: '40a02b' },
    { token: 'number', foreground: 'fe640b' },
    { token: 'type', foreground: '04a5e5' },
    { token: 'function', foreground: '1e66f5' },
    { token: 'variable', foreground: '4c4f69' },
    { token: 'constant', foreground: 'fe640b' },
    { token: 'operator', foreground: '179299' },
    { token: 'delimiter', foreground: '6c6f85' },
    { token: 'tag', foreground: '8839ef' },
    { token: 'attribute.name', foreground: '1e66f5' },
    { token: 'attribute.value', foreground: '40a02b' },
    { token: 'regexp', foreground: 'd20f39' },
  ],
  colors: {
    'editor.background': '#eff1f5',
    'editor.foreground': '#4c4f69',
    'editor.lineHighlightBackground': '#e6e9ef',
    'editor.selectionBackground': '#ccd0da',
    'editor.inactiveSelectionBackground': '#ccd0da80',
    'editorCursor.foreground': '#dc8a78',
    'editorWhitespace.foreground': '#bcc0cc40',
    'editorIndentGuide.background': '#bcc0cc40',
    'editorIndentGuide.activeBackground': '#bcc0cc',
    'editorLineNumber.foreground': '#8c8fa1',
    'editorLineNumber.activeForeground': '#4c4f69',
    'editorWidget.background': '#e6e9ef',
    'editorWidget.border': '#bcc0cc',
    'editorSuggestWidget.background': '#e6e9ef',
    'editorSuggestWidget.border': '#bcc0cc',
    'editorSuggestWidget.selectedBackground': '#ccd0da',
    'editorSuggestWidget.highlightForeground': '#1e66f5',
    'editorBracketMatch.background': '#ccd0da40',
    'editorBracketMatch.border': '#1e66f5',
    'scrollbarSlider.background': '#bcc0cc40',
    'scrollbarSlider.hoverBackground': '#bcc0cc80',
    'scrollbarSlider.activeBackground': '#bcc0ccCC',
  },
};
